version: '3'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  tests:
    build: .
    image: norman
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    command: nimble test

  docs:
    build: .
    image: norman
    volumes:
      - .:/usr/src/app
    command: nimble docs
